---
- hosts: docker1.antegra.com

  tasks:

   - name: Reload api-mocks
     docker:
       name: api-mocks
       image: djordjelavadinovic/api-mocks
       state: reloaded
       pull: always
       ports:
         - 8000:8000
