---
- hosts: dockers

  tasks:

   - name: Reload asee-bpm
     docker:
       name: asee-bpm
       image: djordjelavadinovic/asee-bpm:2
       state: reloaded
       pull: always
       ports:
         - 8888:8080
