---
- name: Install Python and pip
  hosts: all
  tasks:
  
   - name: Copy EPEL yum repo
     command: rpm -Uvh http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm || true

   - name: Install python
     yum: name=python state=latest

   - name: Install pip
     yum: name=python-pip state=latest disable_gpg_check=yes

   - name: Install docker-py module
     pip: name=docker-py
